package logika;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2017-04-23T21:43:21.086+02:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebService(targetNamespace = "http://logika/", name = "Cashier")
@XmlSeeAlso({ObjectFactory.class})
public interface Cashier {

    @WebMethod
    @RequestWrapper(localName = "getCartValue", targetNamespace = "http://logika/", className = "logika.GetCartValue")
    @ResponseWrapper(localName = "getCartValueResponse", targetNamespace = "http://logika/", className = "logika.GetCartValueResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double getCartValue(
        @WebParam(name = "arg0", targetNamespace = "")
        logika.Cart arg0
    );

    @WebMethod
    @RequestWrapper(localName = "discountCart", targetNamespace = "http://logika/", className = "logika.DiscountCart")
    @ResponseWrapper(localName = "discountCartResponse", targetNamespace = "http://logika/", className = "logika.DiscountCartResponse")
    @WebResult(name = "return", targetNamespace = "")
    public logika.Cart discountCart(
        @WebParam(name = "arg0", targetNamespace = "")
        logika.Cart arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getMostExpensiveProduct", targetNamespace = "http://logika/", className = "logika.GetMostExpensiveProduct")
    @ResponseWrapper(localName = "getMostExpensiveProductResponse", targetNamespace = "http://logika/", className = "logika.GetMostExpensiveProductResponse")
    @WebResult(name = "return", targetNamespace = "")
    public logika.Product getMostExpensiveProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        logika.Cart arg0
    );
}
