package logika;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2017-04-23T21:43:21.133+02:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebServiceClient(name = "CashierService", 
                  wsdlLocation = "file:/E:/Repos/JBossRepo/SRI4/wsdl/CashierService.wsdl",
                  targetNamespace = "http://logika/") 
public class CashierService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://logika/", "CashierService");
    public final static QName CashierPort = new QName("http://logika/", "CashierPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/Repos/JBossRepo/SRI4/wsdl/CashierService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CashierService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/Repos/JBossRepo/SRI4/wsdl/CashierService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CashierService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CashierService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CashierService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CashierService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CashierService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CashierService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Cashier
     */
    @WebEndpoint(name = "CashierPort")
    public Cashier getCashierPort() {
        return super.getPort(CashierPort, Cashier.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Cashier
     */
    @WebEndpoint(name = "CashierPort")
    public Cashier getCashierPort(WebServiceFeature... features) {
        return super.getPort(CashierPort, Cashier.class, features);
    }

}
